### PR TITLE
NativeBufferAllocator: release memory when buffer object is GCed

### LINKED ISSUE #64: [CI/CD] A debug-test job
Add a debug-test job to test debug binaries by compiling, assembling, and testing native binaries as debug.

### LINKED ISSUE #65: [Deployment] Deploy a concomitant debug binary with each release
Each release should have a debug version of its binaries.

### LINKED ISSUE #66: [GC] Attach DirectBuffers to GC
Example to utilizing the `java.lang.ref.PhantomReference<T>`.

> Note: the following is a pseudo-code intended to show off the interface and the implementation design.

1) GarbageCollectibleBuffer: A GC PhantomReference wrapping a native buffer.
```java
public class GarbageCollectibleBuffer extends PhantomReference<Buffer> {
      private final Buffer referent;
      private final long address;
      
      private GarbageCollectibleBuffer(final Buffer referent, final ReferenceQueue<? super Buffer> queue) {
              super(referent, queue);
              this.referent = referent;
              this.address = NativeBufferUtils.getMemoryAddress(buffer);
      }

      public static GarbageCollectibleBuffer from(final Buffer buffer, final ReferenceQueue<? super Buffer> queue) {
             if (!buffer.isDirect()) {
                throw new UnSupportedBufferException("Target Buffer isnot a direct Buffer!");
             }
             return new GarbageCollectibleBuffer(buffer, queue);
      }
      
      public static GarbageCollectibleBuffer allocateDirect(final long size, final ReferenceQueue<? super Buffer> queue) {
              final ByteBuffer buffer = NativeBufferUtils.clearAlloc(size);
              return GarbageCollectibleBuffer.from(buffer, queue);       
      }
      
      public void deallocate() {
            NativeBufferUtils.destroy(referent);
      }
      
      public Buffer getReferent() {
           return referent;     
      }
      
      public long getDirectBufferAddress() {
           return address;
      }
}
```

2) GarbageCollectableBuffers: A collection of direct collectible buffers.
```java
public final class GarbageCollectibleBuffers {
      private static ReferenceQueue<Buffer> COLLECTIBLES = new ReferenceQueue<>();
      private final List<GarbageCollectableBuffer> buffers = new ArrayList<>();
      
      private GarbageCollectibleBuffers() {
      }
      
      public static GarbageCollectibleBuffer allocate(final long size) {
            final GarbageCollectibleBuffer collectible = GarbageCollectibleBuffer.allocateDirect(size, COLLECTIBLES);
            buffers.add(collectible);
            return collectible;
      }
      
      public static GarbageCollectibleBuffer register(final Buffer buffer) {
            if (!buffer.isDirect()) {
                   throw new UnSupportedBufferException("Buffer isn't a direct buffer!");
            }
            final GarbageCollectibleBuffer collectible = GarbageCollectibleBuffer.from(buffer, COLLECTIBLES);
            buffers.add(collectible);
            return collectible;
      }

      public static void deallocate(final Buffer buffer) {
            if (!buffers.contains(buffer)) { 
                  throw new UnSupportedBufferException("Buffer is not a direct collectible!");
            } 
            NativeBufferUtils.destroy(buffer);
            buffers.remove(collectible);
      }
      
      public static MemoryScavenger startMemoryScavenger() {
          return MemoryScavenger.start(COLLECTIBLES);
      }
}
```

3) MemoryScavenger: A memory cleaner to help GC scavenge the native memory.
```java
public final class MemoryScavenger extends Thread {
       private final ReferenceQueue<? super Buffer> queue;
        
       private MemoryScavenger(final ReferenceQueue<? super Buffer> queue) {
            super(MemoryScavenger.class.getName());
            setDaemon(true);
            this.queue = queue;
       }
       
       public static MemoryScavenger start(final ReferenceQueue<? super Buffer> queue) { 
            final MemoryScavenger scavenger = new MemoryScavenger(queue);
            scavenger.start();
            return scavenger;
       }
       
       @Override
       public void run() {
            for (;;) {
                // blocks until an object is available in the queue before returning and removing it
                // object references are added to the queue by the GC as a part of post-mortem actions
                GarbageCollectibleBuffer collectible = (GarbageCollectibleBuffer) queue.remove();
                collectible.deallocate();
            }
       }
}
```
------------------------------------------------ JME ------------------------------------------------

4) Implementing the above interface in jme would be super-easy: 

LwjglBufferAllocator: A direct buffer allocator/deallocator for LWJGL-2.
```java
public class LwjglBufferAllocator implements BufferAllocator {
        static {
            GarbageCollectibleBuffers.startScavenger();
        }
        
        @Override
        public ByteBuffer allocate(final int size) {
            return GarbageCollectibleBuffer.register(size).getReferent();
        }
        
        @Override
        public void destroyDirectBuffer(final Buffer buffer) {
            NativeBufferAllocator.release(buffer);
        }
}
```

AndroidNativeBufferAllocator: A native buffer allocator/deallocator for android.
```java
public class AndroidNativeBufferAllocator implements BufferAllocator {
        static {
            GarbageCollectibleBuffers.startScavenger();
        }
        
        @Override
        public ByteBuffer allocate(final int size) {
            return GarbageCollectibleBuffers.allocate(size).getReferent();
        }
        
        @Override
        public void destroyDirectBuffer(final Buffer buffer) {
             GarbageCollectibleBuffers.deallocate(buffer);
        }
}
```

### PR DESCRIPTION
**Pull request by Ali-RS**
Fix #66 

There are 2 TODOs remaining to be fixed.

### CODE REVIEW

**Comment by pavly-gerges** [comment]
Hello @Ali-RS, thanks for the PR.
If you would like to continue to fix this issue, please kindly follow the code design illustrated on issue #66, the code should be similar to the one on the issue (ofc with your own optimizations), and we need an example at `jme3-alloc-examples` to test the code.

**Comment by Ali-RS** [comment]
>please kindly follow the code design illustrated on issue https://github.com/Software-Hardware-Codesign/jme-alloc/issues/66, the code should be similar to the one on the issue

Hi @Scrappers-glitch, this PR is designed based on the JME LWJGL 3 buffer allocator, I am not sure I can follow the approach illustrated on issue https://github.com/Software-Hardware-Codesign/jme-alloc/issues/66 as I do not understand it fully. Please feel free to close this PR if you prefer a different implementation. Thanks

**Comment by pavly-gerges** [comment]
> > please kindly follow the code design illustrated on issue #66, the code should be similar to the one on the issue
> 
> Hi @Scrappers-glitch, this PR is designed based on the JME LWJGL 3 buffer allocator, I am not sure I can follow the approach illustrated on issue #66 as I do not understand it fully. Please feel free to close this PR if you prefer a different implementation. Thanks

No problem, I will try to continue on this PR and add the intended design.

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+
+/**
+ * A collection utility of GC-registered-direct buffers, the collection list is provided through
+ * the registered direct buffers addresses, direct buffers are added to a ReferenceQueue that is 
+ * registered to the GC as a part of post-mortem actions.
+ * 
+ * @author pavl_g
+ */
+public final class GarbageCollectibleBuffers {
+    private final Logger LOGGER = Logger.getLogger(GarbageCollectibleBuffers.class.getName());
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: logger should be a final static field.

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+    private final Map<Long, GarbageCollectibleBuffer> BUFFER_ADDRESSES = new HashMap<>();
+    private final ReferenceQueue<Buffer> COLLECTIBLES = new ReferenceQueue<>();
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: I think the above fields' names should be camelCase as they are non-static.

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/MemoryScavenger.java [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+/**
+ * Provides a thread that is synchronized with the GC to de-allocate a previously 
+ * registered {@link GarbageCollectibleBuffer}, the thread blocks until the buffer 
+ * reference is added to the queue by the GC as a part of post-mortem actions, then it 
+ * acts upon the reference to de-allocate the original native memory from the native-heap.
+ * 
+ * @author pavl_g
+ */
+final class MemoryScavenger extends Thread {
+    private final Logger LOGGER = Logger.getLogger(MemoryScavenger.class.getName());
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/gc/MemoryScavenger.java]: logger should be a final static field.

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java (hunk 1 above)
Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: I refactored the `GarbageCollectibleBuffers` and `MemoryScavenger` to be pure object-oriented classes so that no static members should be used, Should we still use static in the case of the logger object?

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java (hunk 2 above)
Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: Yes, you are right, I messed this up.

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: The logger should be also renamed to `logger` according to the google style of code, it is not a constant, a constant is defined as an immutable primitive data type or object wrapper of immutable fields.
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java (hunk 1 above)
Comment (Ali-RS) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: If you check JME code or for example any of pspeed projects, `logger` is always declared as `static final`. 

Edit:
https://owasp.org/www-community/vulnerabilities/Poor_Logging_Practice

File: jme3-alloc/src/main/java/com/jme3/alloc/NativeBufferAllocator.java [hunk 4]
```diff
@@ -33,17 +33,27 @@
...
  * 
  * @see com.jme3.alloc.util.NativeBufferUtils
  * @author pavl_g
  */
-public final class NativeBufferAllocator {
-    
-    private NativeBufferAllocator() {
+public class NativeBufferAllocator {
+
+    protected final GarbageCollectibleBuffers COLLECTIBLE_BUFFERS = new GarbageCollectibleBuffers();
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/NativeBufferAllocator.java]: The above field name should also be camelCase.

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+     * from the list.
+     * 
+     * @param bufferAddress the buffer memory address
+     * @param isScavenger true if the stack-caller is the {@link MemoryScavenger} thread 
+     *                    associated with this collection, false otherwise.
+     */
+    public void deallocate(long bufferAddress, boolean isScavenger) {
+        /* return if the buffer is not in the list of the collectibles */
+        if (!bufferAddresses.containsKey(bufferAddress)) {
+            log(Level.SEVERE, "Buffer " + bufferAddress + " is not found!", isScavenger);
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: Further optimization could be done here to prevent unnecessary String objects creation in `"Buffer " + bufferAddress + " is not found!"` if `isScavenger` is true.

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: This is an automatic local variable that is destructed immediately once the execution goes beyond this block, so there should be no impact so far, however, if you still want to optimize it, we could simply move the string message to the function log, but that would restrict the function to only this message.

Comment (Ali-RS) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: You can do it like:

```
if (!isScavender) {
    logger.log(Level.SEVERE, "Buffer " + bufferAddress + " is not found!");
}
```

no need for extra `private void log(Level level, String msg, boolean disabled)` method.

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: I don't prefer nested blocks `{ }`, that is why I haven't suggested it in the first place, but I think it's okay here, the code is not that complex.

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffer.java [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+import com.jme3.alloc.util.NativeBufferUtils;
+
+/**
+ * A direct buffer wrapper that registers a direct buffer to be GC'ed by adding 
+ * it to a reference queue. 
+ * 
+ * @author pavl_g.
+ */
+final class GarbageCollectibleBuffer extends PhantomReference<Buffer> {
+    private long memoryAddress;
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffer.java:46]: `long memoryAddress` can be made final.

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffer.java:46]: Done

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+/**
+ * A collection utility of GC-registered-direct buffers, the collection list is provided through
+ * the registered direct buffers addresses, direct buffers are added to a ReferenceQueue that is 
+ * registered to the GC as a part of post-mortem actions.
+ * 
+ * @author pavl_g
+ */
+public final class GarbageCollectibleBuffers {
+    private static final Logger logger = Logger.getLogger(GarbageCollectibleBuffers.class.getName());
+    private final Map<Long, GarbageCollectibleBuffer> bufferAddresses = new HashMap<>();
```
Comment (Ali-RS) [inline jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: As mentioned earlier, you should use a `ConcurrentHashMap` for `bufferAddresses` for it to be safe when accessed from different threads.

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: But, why? we already synchronize the allocate/release on `ConcurrentNativeBufferAllocator`, so all calls here are synchronized by the  `ConcurrentNativeBufferAllocator`.

Comment (Ali-RS) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: Because MemoryScavenger thread calls `collectibles.deallocate()`.

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: I wonder what other calls might be synchronized with this?

Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: If we are going to synchronize the `GarbageCollectibles` HashMap, then I think its better to synchronize the whole coding blocks by adding synchronized on the register and deallocate or at least the deallocate calls, but I need to find a strong reason to do this and understand what are the 2 parties that we are trying to synchronize here.

**Comment by pavly-gerges** [comment]
@Ali-RS I would like to release the gamma version and the final stable version during this week, so please, could you help me by adding the examples you suggested on forums at the `jme3-alloc-examples` module, thank you.

**Comment by Ali-RS** [comment]
>I would like to release the gamma version and the final stable version during this week

I think we should not rush, there are still issues that need to be fixed.

See: https://hub.jmonkeyengine.org/t/jme-alloc-project/46356/180?u=ali_rs

File: jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java (hunk 7 above)
Comment (pavly-gerges) [reply jme3-alloc/src/main/java/com/jme3/alloc/gc/GarbageCollectibleBuffers.java]: @Ali-RS I synchronized the `deallocate` stacks using monitor locks instead, they are now thread-safe, I will mark this as resolved, if, in doubt, you can always re-open the discussion.

**Comment by pavly-gerges** [comment]
@Ali-RS Thanks for your contributions, this PR will be merged for now, if you want to inquire about the API status don't hesitate to ping me on the forums or here on a new issue, Have a great day!
